metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: images/train2021
  anno_path: annotations/head_train2021.json
  dataset_dir: dataset/ppfall_coco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: images/val2021
  anno_path: annotations/head_val2021.json
  dataset_dir: dataset/ppfall_coco
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/label_list.txt # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/ppfall_coco # if set, anno_path will be 'dataset_dir/anno_path'
